[build-system]
requires = [
    "setuptools~=80.9.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyonvista-v2"
version = "2.0.0"
authors = [
  { name="Simon Bauer", email="seimen@cloasdata.de" },
  { name="Jan Philipp Tebbe", email="info@thukyd.com" }
]
maintainers = [
  { name="Jan Philipp Tebbe", email="info@thukyd.com" }
]
description = "Enhanced Python API for OnVista financial data with comprehensive fundamental analysis capabilities"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.8.1"
]
keywords = [
    "finance", "stocks", "financial-data", "onvista", "german-stocks", 
    "fundamental-analysis", "esg", "financial-ratios", "stock-analysis",
    "investment", "trading", "market-data"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Office/Business :: Financial",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
license = "MIT"

[project.optional-dependencies]
test = [
    "pytest >= 7.0.0",
    "pytest-asyncio >= 0.21.0"
]
dev = [
    "pytest >= 7.0.0",
    "pytest-asyncio >= 0.21.0",
    "black",
    "isort",
    "mypy"
]

[project.urls]
Homepage = "https://github.com/Thukyd/pyOnvista"
Repository = "https://github.com/Thukyd/pyOnvista"
Documentation = "https://github.com/Thukyd/pyOnvista#readme"
"Bug Tracker" = "https://github.com/Thukyd/pyOnvista/issues"
Changelog = "https://github.com/Thukyd/pyOnvista/releases"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
